### ISSUE TITLE
Demo.sln does not build

### ISSUE THREAD

**Issue by DJDoena** [Azure/autorest.csharp#1114] opened 2021-04-01 13:05 UTC
**Describe the issue or request**
Downloaded feature/v3 branch 
https://github.com/Azure/autorest.csharp.git

Tried to build 
autorest.csharp\samples\CognitiveSearch\Demo\Demo.sln

Error	CS0122	
'ClientDiagnostics' is inaccessible due to its protection level
autorest.csharp\src\assets\Generator.Shared\ArmOperationHelpers.cs	31

**Comment by chamons** [comment] 2021-04-16 21:55
Hmm, it seems to build for me (and our CI).

Could you attach a full build long, dotnet --version, and what version of npm you have installed?

**Comment by DJDoena** [comment] 2021-04-17 05:21
Node.js v14.16.1.
npm@6.14.12

**Comment by DJDoena** [comment] 2021-04-17 05:25
[logs.zip](https://github.com/Azure/autorest.csharp/files/6328661/logs.zip)

**Comment by DJDoena** [comment] 2021-04-17 05:26
dotnet 5.0.104

**Comment by chamons** [comment] 2021-04-19 15:31
Hmm, it looks like you are resolving the wrong nuget version:

2>            C:\Users\djdoe\.nuget\packages\azure.core\1.0.0\lib\netstandard2.0\Azure.Core.dll
2>                    OriginalItemSpec=C:\Users\djdoe\.nuget\packages\azure.core\1.0.0\lib\netstandard2.0\Azure.Core.dll

The latest azure.core is:

C:\Users\chhamo\.nuget\packages\azure.core\1.13.0\lib\netstandard2.0\Azure.Core.dll

Could you try [resetting your nuget cache](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders#clearing-local-folders) and rebuild?

**Comment by chamons** [comment] 2021-04-19 15:33
Correction - I was mistaken. 

This is a confirmed issue. The csproj reference is stale.

**Comment by chamons** [comment] 2021-04-19 15:37
PR is up resolving the issue. Sorry for the trouble.

**Closed** 2021-04-20 16:04 UTC
Labels: v3
