### ISSUE TITLE
Handle `x-ms-pageable` when `nextLinkName` is null

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.csharp#3140] opened 2023-02-17 03:45 UTC
According to the [doc](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-pageable): 
`If the model does not have a next link property then specify null. This is useful for services that return an object that has an array referenced by itemName. The object is then flattened in a way that the array is directly returned, no paging is used. This provides a better client side API to the end user.`

No paging is used when `nextLinkName` is null. The generator currently treats such case as pageable.

**Comment by ArcturusZhang** [comment] 2023-02-17 09:09
In my understanding `nextLinkName: null` is a placeholder for a paging operation to leave some place for future iteration that enables paging for this operation. They could just add a new property and change this nextlinkname to the real property name, and our generated SDK will not have a breaking change. This should be expected, we generate paging operation if there is x-ms-pageable.
And if you remember, in mgmt plane, we even generate those operations which have response that looks like a pageable one as pageable operations. Therefore I believe this is definitely expected behaviour

**Comment by fengzhou-msft** [comment] 2023-02-17 09:58
> In my understanding `nextLinkName: null` is a placeholder for a paging operation to leave some place for future iteration that enables paging for this operation. They could just add a new property and change this nextlinkname to the real property name, and our generated SDK will not have a breaking change. This should be expected, we generate paging operation if there is x-ms-pageable.
> 
> And if you remember, in mgmt plane, we even generate those operations which have response that looks like a pageable one as pageable operations. Therefore I believe this is definitely expected behaviour

Got it. It's by design. The original issue is from a Post request that is also an LRO, then the generator throws pageable LRO not supported error. Service team said the result is actually not pageable with the nextLinkName as null.

We can probably do something to detect pageable LRO case and improve the error message to tell users to use directive to remove x-ms-pageable if it's not really pageable before we can support pageable LRO in generator.

**Comment by ArcturusZhang** [comment] 2023-02-17 14:53
> > In my understanding `nextLinkName: null` is a placeholder for a paging operation to leave some place for future iteration that enables paging for this operation. They could just add a new property and change this nextlinkname to the real property name, and our generated SDK will not have a breaking change. This should be expected, we generate paging operation if there is x-ms-pageable.
> > And if you remember, in mgmt plane, we even generate those operations which have response that looks like a pageable one as pageable operations. Therefore I believe this is definitely expected behaviour
> 
> Got it. It's by design. The original issue is from a Post request that is also an LRO, then the generator throws pageable LRO not supported error. Service team said the result is actually not pageable with the nextLinkName as null.
> 
> We can probably do something to detect pageable LRO case and improve the error message to tell users to use directive to remove x-ms-pageable if it's not really pageable before we can support pageable LRO in generator.

Well pageable LRO is not supported, this is hard coded in our code because we do not have such resources to support it and it is quite rare in mgmt plane SDKs.
See here: https://github.com/Azure/autorest.csharp/blob/7bd024de629af5a1d35352a5f6e5d576e615536e/src/AutoRest.CSharp/Mgmt/Generation/MgmtClientBaseWriter.cs#L525

@archerzz is doing something around LRO pageable operations in dpg, mgmt plane could also benefit once he is done.

**Comment by ArcturusZhang** [comment] 2023-02-24 02:52
I would like to close this since this is by design

**Closed by ArcturusZhang** 2023-02-24 02:52 UTC
