### ISSUE TITLE
Test server runs in parallel so coverage loses 

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2119] opened 2022-03-29 03:18 UTC
I'm looking into this because I found the DPG coverage in dashboard is only 16% (which should be 83% because we only lack of LRO, and this number matches local coverage run). Looking into the C# test framework, there are two issues:
1. After each test run (and it will save the coverage data into a file), we call [TestServerSession.DisposeAsync](https://github.com/Azure/autorest.csharp/blob/2886a5249cbbfcf8417948b7f4b8565a4191fee3/test/AutoRest.TestServer.Tests/Infrastructure/TestServerSession.cs#L94), in which we call [/report/clear](https://github.com/Azure/autorest.csharp/blob/2886a5249cbbfcf8417948b7f4b8565a4191fee3/test/AutoRest.TestServer.Tests/Infrastructure/TestServerV1.cs#L101) to server. This call will clear all the coverage data we collect for the previous tests. This issue could be quickly work around by fix: [[Don't merge] Fix test coverage by pshao25 · Pull Request #2114 · Azure/autorest.csharp (github.com)](https://github.com/Azure/autorest.csharp/pull/2114/files)[](https://github.com/Azure/autorest.csharp/pull/2114/files)

2. We have parallel run attribute at [TestServerTestBase](https://github.com/Azure/autorest.csharp/blob/0ddfcc9f59af1c47724a266cb2d3b2d657746ecc/test/AutoRest.TestServer.Tests/Infrastructure/TestServerTestBase.cs#L17), which means there are several threads running for tests and we don't know how many. Even we fix the first issue, then the last finished thread still wins to overwrite the previous coverage data. I put details in https://github.com/Azure/autorest.csharp/issues/2090#issuecomment-1078591782. But this attribute only impacts non-DPG tests.

Our current decision is:
1. Fix Pt.1 to unblock DPG
2. Create this issue to fix test framework issue.

**Comment by chunyu3** [comment] 2023-08-22 09:20
The issue is resolved. close this.

**Closed by chunyu3** 2023-08-22 09:20 UTC
Labels: v3, DPG, Epic: Create test infrastructure, WS: Code Generation
