### ISSUE TITLE
Support Replace Common Types

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1629] opened 2021-10-22 07:54 UTC
CLI and powershell has examples of how they did this

- Set of operations that should be attached to resources that work with private link
- set of operations to query private links given resource is attached to
- Models around private link (similar to what we have for managed identity)
- autorest needs to be updated to generate the new operations

**Comment by archerzz** [comment] 2021-11-01 13:24
After a quick glimpse of existing definitions regarding private link, I'm wondering whether we can extract common types for it.

So far, there are two problems:

## Inconsistent Definition

For example, the `PrivateLinkResource` has different properties under different RPs:
- In `appconfiguration`, the [PrivateLinkResource](https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/preview/2019-11-01-preview/appconfiguration.json#L1496) has `requiredZoneNames` property.
- In `automation`, the [PrivateLinkResource](https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/automation/resource-manager/Microsoft.Automation/preview/2020-01-13-preview/privateLinkResources.json#L129) doesn't have that property.

## Different Instances Between RPs

Even we can extract common types, the instances are not transferrable between different RPs.

For example, the typical user scenario of `PrivateServiceConnection` is as follows:
- In `Network`, create a private endpoint in `Network`.
- In `Network`, create a private service connection between the private endpoint and the target service.
- In the target service, approve the private service connection (let's assume is manual approval required).

The problem is that the private service connection you created in `Network` is actually different from the one you get under the target service. Their `Id` and `Name` properties are different. If you have an instance of the connection from `Network`, you cannot operate the one under the target service RP, and vice versa.

So the common way to process the private service connection under target service is to list all connections, and then operate the one you want to change. See the [test case of private service connection](https://github.com/archerzz/azure-sdk-for-net/blob/e364874a783c8e34e5a7e69bfe69c557a3e1c436/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/tests/ScenarioTests/PrivateEndpointConnectionTests.cs#L62) under `cosmos-db` for details.

**Comment by allenjzhang** [comment] 2021-11-05 19:14
When NRP team started private link initiative, our team got involved a little late on the technical side. So some of the RP already diverged. But discussing with Arthur Ning, ARM, and NRP 10 mos ago, it was still desired to have a standard for new RP to adopt. Hence the `privatelink` models have been added to the rest API common types. It is the hope that thru swagger review particularly for new onboard services, we steer them to the common type.  Having said that, I do not know how rigorously it is been enforced to date. Arthur can shed some light on this.

If we all agree that the desire and enforcement are still being pursued, then track 2 should have a standard implementation for those chosen the common definition. Whether is before GA or add after GA would be up to how many RPs adopt this.

If not, we decide to leave this out, we should consider some kind of prefix to disambiguate them. I suspect the developers won't appreciate looking at a list of same-named classes from different RP in the IntelliSense dropdown.

**Comment by allenjzhang** [comment] 2021-11-05 19:46
When NRP team started private link initiative, our team got involved a little late on the technical side. So some of the RP already diverged. But discussing with Arthur Ning, ARM, and NRP 10 mos ago, it was still desired to have a standard for new RP to adopt. Hence the `privatelink` models have been added to the rest API common types. It is the hope that thru swagger review particularly for new onboard services, we steer them to the common type.  Having said that, I do not know how rigorously it is been enforced to date. Arthur can shed some light on this.

If we all agree that the desire and enforcement are still being pursued, then track 2 should have a standard implementation for those chosen the common definition. Whether is before GA or add after GA would be up to how many RPs adopt this.

If not, we decide to leave this out, we should consider some kind of prefix to disambiguate them. Developers probably prefer not to look at a list of same named classes from different RP in the IntelliSense dropdown.

**Comment by archerzz** [comment] 2021-11-08 03:14
Thanks @allenjzhang !

I confirmed with Arthur Ning's team. They have already applied a few rules to enforce consistent private link definitions across RPs.
- [R4035 PrivateEndpointResourceSchemaValidation](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/openapi-authoring-automated-guidelines.md#r4035)
- [R4036 ImplementPrivateEndpointAPIs](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/openapi-authoring-automated-guidelines.md#r4036)

---

Also, I check with Java SDK team. They have common interfaces for `PrivateLinkResource` and `PrivateLinkConnection` in core package. The difference is that part of Java SDK is manually written, so they can write some codes to fix the inconsistence between the standard definitions and each RP's own definitions. 
I think for .net SDK, we can follow the our convention: let `autorest.csharp` extract common types for private links as much as possible. If an RP has very different definition, we won't cover the gap. Later on, if the RP fixes the inconsistency, that is a breaking change in REST API, and thus it won't be a problem to have the corresponding breaking change in SDK. Considering the private link resource instances are not transferrable between RPs (see above), we should not worry too much about interface changes.

**Comment by archerzz** [comment] 2021-11-08 03:18
By the way, the `Network` uses different `Resource` definitions (e.g. `Id`, `Name` are writable), so that it will still have its own private link definitions. I think this is a known issue not restricted to private link resources. Also the private link connection created by `Network` cannot be re-used in other RPs. So, I think this should be acceptable.

**Comment by archerzz** [comment] 2021-11-16 01:49
Have some trial and it was not successful. The problem is found: our current type replacement logic will work for the following two scenario:
- Type Foo is used as a property type
- Type Foo is used as a base class

Private link resources do not belong to the above cases. They are used standalone. So they won't be replaced. We need to modify the logic to replace the `MgmtObjectType` if it fits certain comment type.

Java SDK doesn't have this problem, because private link resource classes are written by hand.

**Comment by archerzz** [comment] 2021-12-14 12:45
Per discussion, it's not worth the efforts to replace `PrivateEndpointConnection` or `PrivateLinkResource`, because:

1. Class type replacement is fragile, a little difference in swagger definition can fail it. See the statistics table below. For 5 RPs (with 3 classes of types to replace) we've tried, there are only **2** thorough replacement and **2** partial replacement, **out of 15 cases**. All the others fail due to various reasons.

RP Name | PrivateEndpointConnection/PrivateEndpointConnectionListResult | PrivateLinkResource/PrivateLinkResourceListResult | CheckNamAvailability
-- | -- | -- | --
Cosmos | Excessive   "groupId" property, see   https://github.com/archerzz/azure-rest-api-specs/blob/f780b571abddf2fc99233212a00510d3bef6878d/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/privateEndpointConnection.json#L257 | Y | Not a standard API,   see:   https://github.com/archerzz/azure-rest-api-specs/blob/f780b571abddf2fc99233212a00510d3bef6878d/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/cosmos-db.json#L570
Network | "id" of   "Resource" is writable (known issue of network) | N/A | N/A
Compute | Only "PrivateEndpointConnection", because   "PrivateEdnpointConnectionListResult" has "nextLink" | Y | N/A
Storage | "PrivateEndpointConnection.PrivateEndpoint"   is subresource (inlined definition, see:   https://github.com/Azure/azure-rest-api-specs/blob/719b74f77b92eb1ec3814be6c4488bcf6b651733/specification/storage/resource-manager/Microsoft.Storage/stable/2021-04-01/privatelinks.json#L11) | "RequiredZoneNames"   is IList (investigating…) | Not a standard API,   see:   https://github.com/Azure/azure-rest-api-specs/blob/603a4b41fe1100e273b79ef2de752710af724648/specification/storage/resource-manager/Microsoft.Storage/stable/2021-04-01/storage.json#L82
DeviceUpdate | Failed,   because in v3 types, "Resource" has a "systemData"   property | same | Only CheckNameAvailabilityResponse   can be replaced.     Cannot replace CheckNameAvailablityRequest, because "type"   property is of    "ResourceType" type instead of "string" in   original **definition**

2. The purpose of type replacement is for polymorphism, consistent interface, and probably other benefits. Just sharing some data structure is not sufficient. Considering private resource operations still belong to each RP, **the bottom line is that we should be able to replace major class types**. We don't want the scenario below that only some secondary types are replaced.
![image](https://user-images.githubusercontent.com/4516/146000153-73b74194-2ee3-4c04-952f-2673dc1b7fd0.png)

3. Based on the business cases of private endpoint, the corresponding object instances are not transferrable between RPs. They are restricted in each RP domain. (See the discussion above in this thread) So if we could not replace them, it's actually not that important since you won't use the type from one RP to another RP.

---

However, the type replacement logic is still useful. We should keep it.

**Comment by archerzz** [comment] 2021-12-20 12:15
This is also related to #1579

**Closed** 2021-12-30 06:03 UTC
Labels: Mgmt, Epic, breaking-change
