### ISSUE TITLE
Failed to build generated track 2 mgmt sdk for Network

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#638] opened 2020-04-07 09:03 UTC
Restore completed in 466.88 ms for C:\AME\erich-net-sdk\sdk\network\Azure.Management.Network\src\Azure.Management.Network.csproj.
Generated\Models\OwaspCrsExclusionEntrySelectorMatchOperator.cs(14,82): error CS0535: 'OwaspCrsExclusionEntrySelectorMatchOperator' does not implement interface member 'IEquatable<OwaspCrsExclusionEntrySelectorMatchOperator>.Equals(OwaspCrsExclusionEntrySelectorMatchOperator)' [C:\AME\erich-net-sdk\sdk\network\Azure.Management.Network\src\Azure.Management.Network.csproj]
Generated\Models\OwaspCrsExclusionEntrySelectorMatchOperator.cs(14,36): error CS0660: 'OwaspCrsExclusionEntrySelectorMatchOperator' defines operator == or operator != but does not override Object.Equals(object o) [C:\AME\erich-net-sdk\sdk\network\Azure.Management.Network\src\Azure.Management.Network.csproj]
Generated\Models\ResourceNavigationLink.cs(27,72): error CS0100: The parameter name 'id' is a duplicate [C:\AME\erich-net-sdk\sdk\network\Azure.Management.Network\src\Azure.Management.Network.csproj]
Generated\Models\VpnServerConfiguration.cs(42,136): error CS0100: The parameter name 'name' is a duplicate [C:\AME\erich-net-sdk\sdk\network\Azure.Management.Network\src\Azure.Management.Network.csproj]

**Comment by MiYanni** [comment] 2020-04-07 21:41
Closing as duplicate of: https://github.com/Azure/autorest.csharp/issues/628
You can see the same errors if you search `OwaspCrsExclusionEntrySelectorMatchOperator`.

**Closed by MiYanni** 2020-04-07 21:41 UTC
