### ISSUE TITLE
Remove dependency on npm for CADL compiler / emitter in nuget package

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2464] opened 2022-07-22 18:47 UTC
`microsoft.azure.autorest.csharp` nuget package contains all the packages required to generate code from swagger, without any dependency on npm or npx, e.g.:
```
node C:\path_to_packages\microsoft.azure.autorest.csharp\3.0.0-beta.20220712.1\tools\autorest\entrypoints\app.js --max-memory-size=8192 --skip-csproj --skip-upgrade-check --version=3.8.4 C:\GitHub\azure-sdk-for-net\sdk\confidentialledger\Azure.Security.ConfidentialLedger\src\autorest.md  --use=C:\path_to_packages\microsoft.azure.autorest.csharp\3.0.0-beta.20220712.1\tools\netcoreapp3.1\any\ --clear-output-folder=true --shared-source-folders="C:\GitHub\azure-sdk-for-net\sdk\core\Azure.Core\src\Shared\;C:\path_to_packages\microsoft.azure.autorest.csharp\3.0.0-beta.20220712.1\content\Generator.Shared\" --output-folder=C:\GitHub\azure-sdk-for-net\sdk\confidentialledger\Azure.Security.ConfidentialLedger\src\Generated --namespace=Azure.Security.ConfidentialLedger
```

We need to have similar independence for the CADL case.

**Comment by pshao25** [comment] 2022-08-01 08:59
Two difficulties here:
1. Autorest is js-based without any other languages. So it could be packed into a single executable by webpack. However, cadl is not because it contains cadl-related libraries.
2. Cadl itself doesn't know the existence of CSharp emitter.

**Comment by lirenhe** [comment] 2022-08-02 06:18
@pshao25,  cadl should be similar to autorest,  for CADL, you just need pack  @cadl-lang\compiler and invoke 
node 'cadl path'\compiler\cmd\cadl.js

Other dependencies should be put together with CADL files and we don't need to put it together with nuget.

**Comment by johanste** [comment] 2022-10-11 22:54
What is the use case for this?

**Comment by pshao25** [comment] 2022-10-12 06:38
@AlexanderSher 
Th difference between a compiler and a tool is: the autorest tool could automatically look for the .net codegen plugin and call it, while compiler cannot do this. The expectation to use cadl compiler is: user provides the cadl spec and a package.json to indicate the compiler version and library version. The libraries should be loaded locally, so we could not pack them (and codegen doesn't know which to pack). The compiler itself could be packed but it is a meaningless thing, because it is the user who indicate its version.

According to above, the best solution to me now is: we could pack the emitter and its dependencies into a single file (as waht we did in https://github.com/Azure/autorest.csharp/pull/2761), and release the bundle file in our nuget package. Then user could generate code by:
1. install the compiler and libraries they want.
2. run `npx cadl compile {cadlFile.cadl} --emit bundle.js --output-path Generated\`
3. run `dotnet AutoRest.CSharp.dll --no-build --standalone Generated\`

We have put the codegen and emitter (with its dependecies) into the package. The things that not covered in package now is only the compiler and libraries. But users still need to provide `Configuration.json` (or we could generate it).

**Comment by lirenhe** [comment] 2022-10-26 00:10
Duplicate of https://github.com/Azure/autorest.csharp/issues/2585

**Closed** 2022-10-26 00:10 UTC
Labels: v3, DPG, DPG/RLC v2.0b2, Epic: Packaging, WS: Code Generation
