### ISSUE TITLE
Examples being generated even if operation is suppressed

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/autorest.csharp#4120] opened 2024-01-10 22:28 UTC
Examples are still generated after the operation that they use is suppressed. 

For example, in the following [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/0373f0edc4414fd402603fac51d0df93f1f70507/specification/monitor/resource-manager/Microsoft.Insights/stable/2023-10-01/metricDefinitions_API.json#L117): 
I suppress the Subscription operations by doing:
### Remove subscription scoped operations

``` yaml
directive:
  - remove-operation: MetricDefinitions_ListAtSubscriptionScope
  - remove-operation: Metrics_ListAtSubscriptionScope
  - remove-operation: Metrics_ListAtSubscriptionScopePost
```
But the examples using the MetricDefinitionsClient are still being generated:
![image](https://github.com/Azure/autorest.csharp/assets/67986960/638a4985-586c-43ab-85d3-696d0700804d)
If we don't have the client - we shouldn't be generating the samples. There is currently no way to not generate the examples using Autorest.

**Comment by ArcturusZhang** [comment] 2024-01-12 09:08
Please open a draft PR in azure-sdk-for-net repo with all the problematic changes and put its link in this issue so that we could reproduce the issue and troubleshoot.
I assume you met this issue when you are trying to migrate your HLC package to DPG because HLC packages do not generate samples like this.

**Comment by nisha-bhatia** [comment] 2024-01-12 21:43
Thank you Dapeng for your response. I made a draft [PR](https://github.com/Azure/azure-sdk-for-net/pull/41227) for the code, the sample file can be found [here](https://github.com/Azure/azure-sdk-for-net/pull/41227/files#diff-e3bef5f03eb6e61e4347eb593c8735a8f6588d647a942b483e83502b67d2ee3c). This is an HLC client and we are not migrating to DPG - Monitor Query been an HLC for several GAs so I'm not sure where the sample files are coming from. The updated autorest files with the Swagger files can be found [here](https://github.com/Azure/azure-sdk-for-net/pull/41227/files#diff-c28f8db4c741228c732387d2118c33196f7648946050b07a71126c5006106b95). Please let me know if you need anything else. Thank you!

**Comment by ArcturusZhang** [comment] 2024-01-13 03:32
Those files are generated by DPG generator only. You must have mistakenly enabled DPG and then disabled it.
Because the autorest generator only cleans up files in `src/Generated` directory, those files in `tests/Generated` will not be cleaned up, which makes an illusion that the generator is always generating those files.
You just need to manually remove those files, and everything should be fine.
Closing the issue

**Closed by ArcturusZhang** 2024-01-13 03:32 UTC
Labels: Client
