### ISSUE TITLE
Deserialize directly to wrapper type

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#476] opened 2020-03-03 19:49 UTC
Instead of needing to do this, for example:

https://github.com/annelo-msft/azure-sdk-for-net/blob/7491e956a085ab5a85bf87508b9b4a8bee1d6439/sdk/template/Azure.Template/src/ExtractedField.cs#L39

**Comment by AlexGhiondea** [comment] 2020-05-18 22:48
Closing as dupe of #671

**Closed by AlexGhiondea** 2020-05-18 22:48 UTC
Labels: v3
