### ISSUE TITLE
[Bug] Setter is generated for collection property

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#4942] opened 2024-07-29 21:42 UTC
As per the [collection properties guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values), collection properties should not be settable. However, in the OpenAI SDK, there is a collection property called `Metadata` of type `IDictionary<string, string>`, and the code generator is generating a setter for this property.

![image](https://github.com/user-attachments/assets/ab7b5040-f5a5-45d7-b949-fe503f3dd201)

For more details refer: https://github.com/joseharriaga/openai-in-typespec/pull/182#discussion_r1693659793

**Comment by ArcturusZhang** [comment] 2024-08-01 07:06
Per offline discussion, the property shown in the screenshot has setter because it is a nullable collection which is by design and expected.
Therefore closing this issue.

**Closed by ArcturusZhang** 2024-08-01 07:06 UTC
Labels: v3
