### ISSUE TITLE
Resolve record test failure for MVAD in CADL+DPG flow

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2879] opened 2022-11-24 08:49 UTC
From service team:

"_After trying to replace the endpoint and key in recorded json file, we think that these 2 problems are caused by recent azure core version upgrade in main branch https://github.com/Azure/azure-sdk-for-net/commit/19e5837f0dba54582650579b17f7f3bbeb21b6ce. 

Problems:

In record mode, variables are updated, yet entry is empty in recorded json file.
In playback mode, new azure core test framework will check the validness of endpoint and key. But the check will always fail because key is recorded as "Sanitized". Key is secrete and cannot be uncovered directly in code repo. We think that the step of checking validness of endpoint and key might be impropriate in playback mode._  "

Please help to investigate the root cause and see how we could solve this problem. thanks

**Comment by chunyu3** [comment] 2023-02-08 05:42
This issue is because of "Santitized" key is not the same in windows and linux. Test Framework resolve this issue. And the issue does not reproduce now. Close it.

**Closed** 2023-02-08 09:41 UTC
Labels: v3, DPG, DPG/RLC v2.0 GA, Epic: Generate tests and samples, WS: Code Generation
