### ISSUE TITLE
Using 0.38 or newer versions of the cadl compiler

### ISSUE THREAD

**Issue by jpalvarezl** [Azure/autorest.csharp#2932] opened 2022-12-10 01:05 UTC
**Describe the issue or request**

Updating cadl-csharp to use cadl compiler `v0.38` and cadl-azure-core `v0.24` would enable us to write cadl that expresses polymorphism more clearly. Currently we are not able to use `alias` or templating features rendering our written cadl difficult to follow.

You can see in the [PR](https://github.com/Azure/azure-rest-api-specs/pull/21609) the changes that we would like to implement for our cadl but we are otherwise blocked due to the compiler version of cadl imposed by the emitter.

**Comment by lirenhe** [comment] 2022-12-12 05:31
duplicate of #2928

**Closed** 2022-12-16 08:30 UTC
Labels: v3, duplicate, DPG, DPG/RLC v2.0 GA
