### ISSUE TITLE
Incomplete name Azure.AI generated instead of Azure.AI.ContentSafety

### ISSUE THREAD

**Issue by mengaims** [Azure/autorest.csharp#3341] opened 2023-05-03 12:49 UTC
When generating sdk project following this [guidance](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/AzureSDKPackage_Setup.md)
The produced content all have the name Azure.AI instead of Azure.AI.ContentSafety.
You can reproduce it by running:
.\eng\scripts\automation\Invoke-TypeSpecDataPlaneGenerateSDKPackage.ps1 -sdkFolder D:\src\mengaims\azure-sdk-for-net\sdk\contentsafety\Azure.AI.ContentSafety -typespecSpecDirectory specification\cognitiveservices\ContentSafety -commit 462e8d9327ea0dfc77e7df76933b34b3d489953e -repo Azure\azure-rest-api-specs-pr
And I pushed the output sdk project [here](https://github.com/mengaims/azure-sdk-for-net/tree/acs/sdk/contentsafety).

I mitigated this issue manually and would appreciate if someone could help me have a check if the fixing is valid: https://github.com/Azure/azure-sdk-for-net/pull/34933

**Comment by catalinaperalta** [comment] 2023-05-03 21:47
cc @m-nash please help us look into this or loop in the right person who could help the team, thanks!

**Comment by chunyu3** [comment] 2023-05-05 03:07
duplicate with https://github.com/Azure/azure-sdk-for-net/issues/35055. The root cause is, in dotnet 7.0.2, When we reference a derived symbol in a symbol generator, the generated symbol value does not contain the derived symbol.

**Comment by heaths** [comment] 2023-05-05 17:43
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/35055

**Closed by heaths** 2023-05-05 17:43 UTC
Labels: v3, DPG
