### ISSUE TITLE
Dependencies from `*.csproj` file prevent successful build

### ISSUE THREAD

**Issue by jpalvarezl** [Azure/autorest.csharp#2931] opened 2022-12-10 00:58 UTC
**Describe the issue or request**

*IMPORTANT NOTE:* the linked [branch ](https://github.com/Azure/azure-rest-api-specs/compare/feature/cognitiveservices/openai-cadl)has updated cadl that does not work with the emitter. If you checkout this branch make sure to use the cadl from [this ](https://github.com/Azure/azure-rest-api-specs/commit/c8cf29cffa7984235514de5ce8cabe715848c2d9) commit

*USEFUL NOTE:* You can find the fully generated folder [here](https://github.com/Azure/azure-sdk-for-net/tree/feature/azure-openAI-inference/sdk/cognitiveservices/Azure.OpenAI.Inference/src)

Attempting to generate an SDK for OpenAI Inference ([link to branch](https://github.com/Azure/azure-rest-api-specs/tree/feature/cognitiveservices/openai-cadl/specification/cognitiveservices/OpenAI.Inference)) generates a project with a `csproj` file that doesn't seem to be correctly setup for the [repository](https://github.com/Azure/azure-sdk-for-net). 

The dependency in question is `Azure.Core` doesn't seem to be correctly imported.  `Microsoft.Azure.AutoRest.CSharp` 

The generated file looks like so:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <IncludeGeneratorSharedCode>true</IncludeGeneratorSharedCode>
    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.AutoRest.CSharp" Version="3.0.0-beta.20221201.1" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.25.0" />
  </ItemGroup>

</Project>
```

**Describe your ideas for solutions**
The target is to generate an SDK for this [repository](https://github.com/Azure/azure-sdk-for-net). The main dependency we need to use is `Azure.Core` but the generated file does not seem to match other SDKs using `Azure.Core`. [Other SDKs](https://github.com/Azure/azure-sdk-for-net/blob/feature/azure-openAI-inference/sdk/agrifood/Azure.Verticals.AgriFood.Farming/src/Azure.Verticals.AgriFood.Farming.csproj) setup seems different

**Comment by lirenhe** [comment] 2022-12-12 05:30
duplicate of #2885

**Comment by chunyu3** [comment] 2023-07-21 07:18
We already support to create compliable project file in scaffolding folder creation. close it.

**Closed** 2023-07-21 07:19 UTC
Labels: v3, duplicate, DPG, DPG/RLC v2.0 GA
