### ISSUE TITLE
Model with BinaryData property cannot be serialized

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2674] opened 2022-09-05 05:57 UTC
This is how the model is [defined](https://github.com/Azure/autorest.csharp/blob/59a2aa9170/test/CadlRanchProjects/property-types/Generated/BytesProperty.cs) (cadl [here](https://github.com/Azure/cadl-ranch/blob/9e5ddbeda8413655341e92392ea288ccc67f2064/packages/cadl-ranch-specs/http/models/property-types/main.cadl#L67)). It has a property wth type `BinaryData`.
```C#
public partial class BytesProperty
{
    public BinaryData Property { get; set; }
}
```
We cannot pass this test case: https://github.com/Azure/autorest.csharp/blob/59a2aa917077017b28a8a90c474673b81f273d85/test/CadlRanchProjects.Tests/property-types.cs#L55-L59
Root cause: same as https://github.com/Azure/autorest.csharp/issues/2447, if we create BinaryData by `BinaryData.FromString("\"aGVsbG8sIHdvcmxkIQ==\"")`, test case could be passed.

**Comment by lirenhe** [comment] 2022-09-05 07:48
It should be solved by https://github.com/Azure/autorest.csharp/issues/2516.  @archerzz, could you help to investigate?

**Comment by archerzz** [comment] 2022-09-05 10:00
It's the same issue in https://github.com/Azure/autorest.csharp/issues/2447

The problem is that the value of `BinaryData.FromString("aGVsbG8sIHdvcmxkIQ==")` must be quoted, otherwise it is not a valid JSON property value.

See more discussion in the linked issue. The conclusion is that we should provide guide doc on how to correctly get a `BinaryData`.

**Comment by lirenhe** [comment] 2022-09-16 07:55
@archerzz, as mgmt. SDK used the same approach and it is approved by archboard, we could take the same approach.
Feel free to close it if there is no additional work needed.
Please create a seperate issue for doc improvement. thanks

**Closed** 2022-09-21 10:34 UTC
Labels: v3, bug, Client, DPG, DPG/RLC August MVP, Epic: Convenience methods with models, WS: Code Generation
