### ISSUE TITLE
Renames of extensible enums don't work

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#4915] opened 2024-07-12 17:32 UTC
Trying to rename https://github.com/Azure/azure-rest-api-specs/blob/abd5157cf12219dcd693b6d8edd5334281110af5/specification/eventgrid/Azure.Messaging.EventGrid.SystemEvents/Microsoft.Communication/AzureCommunicationServices.tsp#L769, with the following property override:

@@clientName(recordingContentType,
  "AcsRecordingContentType",
  "csharp"
);

But it doesn't work. This is specific to csharp - it works for other languages.

**Comment by chunyu3** [comment] 2024-08-06 08:05
Need to investigate TCGC library why @clientName does not work.

**Comment by chunyu3** [comment] 2024-09-09 05:16
Hello @JoshLove-msft I tried locally to rename a extensible enum via `@clientName`, and it works, The issue should be resolved. Would you please help to check? thanks.

**Comment by chunyu3** [comment] 2024-09-24 07:26
Close this because it cannot be reproduced. It should be resolved.

**Closed by chunyu3** 2024-09-24 07:26 UTC
Labels: needs-author-feedback, no-recent-activity, DPG, DPG/RLC v2.1
