### ISSUE TITLE
[Bug] csharp/imodeler1 crash

### ISSUE THREAD

**Issue by allenjzhang** [Azure/autorest.csharp#973] opened 2021-01-09 02:13 UTC
**Describe the issue or request**
When running against a swagger PR, the automation generation fails. 

[PR link](https://github.com/Azure/azure-rest-api-specs-pr/pull/2650)
[Pipeline failure link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=678191&view=logs&j=2be18a23-047c-5c9f-61d7-60a33437d1f1&t=90227b5e-3523-5803-3e16-3788cf693a16)

```
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 142
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.
```

Local repro step. Replace SDK folder and readme.md path accordingly.

```
clone 
git pull origin pull/2650/head:pr2650
git checkout pr2650

autorest --version=V2 --csharp --reflect-api-versions --license-header=MICROSOFT_MIT_NO_VERSION --use=@microsoft.azure/autorest.csharp@2.3.82 --csharp-sdks-folder=c:\temp\pr2650\sdk C:\Github\API\azure-rest-api-specs-pr/specification/dnsresolver/resource-manager/readme.md
```

**Comment by fearthecowboy** [comment] 2021-01-11 17:43
Don't use `allOf` with `$ref` 

``` json

 "allOf": [
            {
              "$ref": "#/definitions/ProvisioningState"
            }
          ]
```

should be something like: 

``` json

 "allOf": [
           "#/definitions/ProvisioningState"
          ]
```

**Comment by guandali** [comment] 2021-01-11 22:14
@fearthecowboy 
Hey Garrett, 
Thank you for the reply, I tested the above suggested changes, and got below issues when running autorest offline: 
![image](https://user-images.githubusercontent.com/12420143/104244302-f9afe500-5416-11eb-969e-4ee4f9612a6a.png)
 
 I searched in the repo: 
 https://github.com/Azure/azure-rest-api-specs/search?p=2&q=allOf
 
 The below format seems pretty standard to me, could you take a look again? Thanks! 
```
"allOf": [
            {
              "$ref": "#/definitions/ProvisioningState"
            }
          ]
```

**Comment by fearthecowboy** [comment] 2021-01-11 23:13
hmm. my mistake, I been out of this for so long, I'm going crazy.

I'm going to have to ask @daviwil to take a look, I actually am not on this team anymore.

**Comment by guandali** [comment] 2021-01-13 01:19
@daviwil 
Hey David,  could you take a look? Thank you!

**Comment by guandali** [comment] 2021-01-13 19:18
Issue have been resolved on our end. 
Debugging steps: 

- Added `--v3` flag like below 
`autorest --csharp C:\Networking\DNS\azure-rest-api-specs-pr\specification\dnsresolver\resource-manager\readme.md  --v3`
Found issue was caused by ancestor issue in ProvisioningState ref. 

Please refer to this commit for the fix.

**Comment by guandali** [comment] 2021-01-13 19:18
Please close it accordingly.

**Comment by daviwil** [comment] 2021-01-13 19:32
Glad you got it resolved!  I'll close it for now, let us know if you run into any further issues.

**Closed by daviwil** 2021-01-13 19:32 UTC
Labels: Mgmt, v2
