### ISSUE TITLE
Duplicate test projects are generated for DPG library

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#3924] opened 2023-11-14 01:29 UTC
When generating the Azure.Messaging.EventGrid.Namespaces project, which ultimately is pulled in to Azure.Messaging.EventGrid via shared source (and isn't shipped on its own), two separate test projects are generated. Here is the [tspconfig](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/Azure.Messaging.EventGrid/tspconfig.yaml#L26-L29). One of the test projects is Azure.Messaging.EventGrid.Namespaces.Tests, and the other is EventGrid.Tests. EventGrid.Tests references a non-existant EventGrid.csproj which causes compilation errors. I can't manually delete EventGrid.Tests because then CI fails due to the generated code not matching. Azure.Messaging.EventGrid.Namespaces.Tests builds without issue.

**Comment by chunyu3** [comment] 2023-11-14 02:15
Hello @JoshLove-msft How do you generate the library? When ` Azure.Messaging.EventGrid.Namespaces` is a new project, you need to create the project folder named ` Azure.Messaging.EventGrid.Namespaces` under azure-sdk-for-net repo, and then generate the code with `dotnet build /t:GenerateCode`.

**Comment by JoshLove-msft** [comment] 2023-11-14 02:16
Here is the project structure - https://github.com/Azure/azure-sdk-for-net/tree/feature/eventgrid/namespaces/sdk/eventgrid/Azure.Messaging.EventGridV2

**Comment by chunyu3** [comment] 2023-11-14 02:17
> Here is the project structure - https://github.com/Azure/azure-sdk-for-net/tree/feature/eventgrid/namespaces/sdk/eventgrid/Azure.Messaging.EventGridV2

Hello @JoshLove-msft  the project folder name should be the same as namespace, so it should be `Azure.Messaging.EventGrid.Namespaces`.

**Comment by chunyu3** [comment] 2023-11-20 06:14
Hello @JoshLove-msft Any further issues about this? If not, we may close this. Thanks

**Comment by JoshLove-msft** [comment] 2023-11-28 15:15
Feel free to close - I will reopen if I run into any issues.

**Comment by chunyu3** [comment] 2023-11-29 05:55
The issue is resolved. Close it.

**Closed by chunyu3** 2023-11-29 05:55 UTC
Labels: v3, customer-reported, DPG, DPG/RLC v2.1
