### ISSUE TITLE
Initialize collection values by default

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#729] opened 2020-05-05 20:38 UTC
Required collections should not become a constructor parameter and instead be an always initialized read-only property.

If property type is nullable property should be settable but still be initialized by default.

For optional not nullable properties empty collection should be treated as omitted.
For optional nullable properties empty collection should be sent.

**Comment by AlexGhiondea** [comment] 2020-05-18 22:27
Duplicate of #521

**Closed by AlexGhiondea** 2020-05-18 22:27 UTC
Labels: v3, 💥 API Impact
