### ISSUE TITLE
Incorrect IsReadOnly flag in the output of cadl emitter

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2573] opened 2022-08-12 09:37 UTC
https://github.com/Azure/autorest.csharp/blob/3ba38068e6de0683c2b5cd39a36d676b23941b64/test/TestProjects/CadlPetStore/Generated/cadl.json#L26

This should not be true.

**Comment by chunyu3** [comment] 2022-08-17 08:01
visiblity decorator  is supported. The issue is resolved. close it.

**Closed by chunyu3** 2022-08-17 08:01 UTC
Labels: v3, DPG, DPG/RLC August MVP
