### ISSUE TITLE
Provide design for PATCH operation models from TypeSpec

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2492] opened 2022-07-26 18:41 UTC
The August MVP target service has PATCH operations. We need to determine whether we will provide special model support for PATCH operations.

This may have already been decided in https://github.com/Azure/azure-sdk/issues/3520#issuecomment-1061373039.
There is a relevant document from @JeffreyRichter as well.

**Comment by annelo-msft** [comment] 2022-08-04 19:50
- Can we have models that are used in both create and update, but that allow you to set the property for create but not for update?

**Comment by JeffreyRichter** [comment] 2022-08-04 21:41
Yes. PACTH can be used for both create and update; POST/PUT isn't even necessary for service to support at all. So, the 1st PATCH creates and further PATCHes update. We tell services that if a PATCH body includes a property that is "create-only" to accept it if its value matches what's already there (the retry scenario) else to fail the request with a 400.




  *   Jeffrey Richter<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fjeffrichter%2F&data=04%7C01%7Cjeffreyr%40microsoft.com%7Ce7fceff8355e42b58e9808d9984c1c42%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637708274948105702%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0%2FoNrFB9XBjrOL6%2BhAKPjBjo3v64zUKh3iCT4iOQEaU%3D&reserved=0> (see Architecting Distributed Cloud Apps<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FRichterCloudApps&data=04%7C01%7Cjeffreyr%40microsoft.com%7Ce7fceff8355e42b58e9808d9984c1c42%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637708274948115662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hi5sNLwenwmaeAJbOD%2BDqypy0S3GAJc2JSXT4zx%2FOfE%3D&reserved=0> & Designing HTTP APIs<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9Ng00IlBCtw%26list%3DPL9XzOCngAkqs4m0XdULJu_78nM3Ok3Q65%26index%3D1&data=04%7C01%7Cjeffreyr%40microsoft.com%7Ce7fceff8355e42b58e9808d9984c1c42%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637708274948115662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yC7ePBu%2FXF7ZqU%2BinXidIFzPnztL0%2BcpiIVqGJkN2qk%3D&reserved=0>)


Azure API Stewardship: Guidelines<https://aka.ms/azapi/guidance>  |  Review process <https://aka.ms/azapi>  |  Recordings<https://aka.ms/azapi/teams>  |  Calendar<https://aka.ms/azapi/calendar>  |  Join the Interest Group<https://aka.ms/azapi/join-interest-group>

Azure SDK Architecture: Guidelines<https://azure.github.io/azure-sdk/general_introduction.html>  |  Review process <https://aka.ms/azsdk/archreview/process>  |  Recordings<https://aka.ms/azsdk/archreview/recordings>  |  Calendar<https://aka.ms/azsdk/archreview/calendar>  |  Join the Interest Group<https://aka.ms/azsdk/archreview/join-interest-group>

________________________________

**Comment by lirenhe** [comment] 2022-10-12 09:20
CADL is defining the merge-patch body in https://github.com/Azure/cadl-azure/blob/main/packages/cadl-azure-core/lib/operations.cadl#L49-L64

Foundations.ResourceCreateOrUpdateModel applies to the resource type, inside the definition, CADL  remove  properties with read visibility and make all the other required properties as optional.

https://github.com/Azure/cadl-azure/blob/main/packages/cadl-azure-core/lib/foundations.cadl#L123-L125

TypeScript plan to generate the model type as

interface TResourceMergeAndPatch = Partial<Exclude<TResource, "">>;
interface TResourcePatch = Exclude<TResource, "">;

We shall decide how we could handle this case in dotnet.

**Comment by lirenhe** [comment] 2023-02-03 06:43
Move out of GA as this is not high priority for now

**Comment by chunyu3** [comment] 2023-05-17 09:44
We will use `DynamicData` to implement patch operation and operation with merge-patch content-type. `DynamicData` will be supported in Azure.Core end of June (maybe). We will delay supporting patch operation and merge-patch until `DynamicData` is released in Azure.Core.

**Comment by lirenhe** [comment] 2023-06-09 03:11
I found a couple of patch operations in another service (LoadTest):  https://github.com/Azure/azure-rest-api-specs/blob/feature/loadtesting/specification/loadtestservice/routes.tsp

Though we could still generate protocal methods for the user but that may impact the usablilty, as this is a missing feature,  I hope the Patch support could be ready ASAP.

cc @mikekistler  @m-nash

**Comment by lirenhe** [comment] 2023-06-12 09:17
ContentSafety also contains the patch API. Currently, we only generate protocal methods for them.

https://github.com/Azure/autorest.csharp/issues/3344

**Comment by m-nash** [comment] 2023-06-13 17:09
@lirenhe can you write up what code a customer would have to do for various patching scenarios to work with protocol methods?  I think this would help everyone understand our current state and how good or bad it currently is.

**Comment by lirenhe** [comment] 2023-06-14 05:48
> @lirenhe can you write up what code a customer would have to do for various patching scenarios to work with protocol methods? I think this would help everyone understand our current state and how good or bad it currently is.

I am not the expert in this area, but below are what are service teams shows how to use the protocal patch operation:

https://github.com/Azure/azure-sdk-for-net/blob/8962d4f567cc7acc60cda3308766cdfef2e69b8c/sdk/contentsafety/Azure.AI.ContentSafety/tests/Samples/Sample3_ManageBlocklist.cs#L34

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/loadtestservice/Azure.Developer.LoadTesting/samples/Sample3_CreateOrUpdateAppComponent.md

**Comment by annelo-msft** [comment] 2023-06-19 17:31
Thank you for these, @lirenhe!

Since DynamicData has released, I'd like to start sketching out this design now.  It would be good for me to get a holistic understanding of how PATCH operations show up in our generated libraries.  
- Are these two libraries - Azure.AI.ContentSafety and Azure.Developer.LoadTesting the only two we're currently tracking that have PATCH operations, or are there others?  
- Are they primarily used for CreateOrUpdate operations, or do they show up in any other ways?
- Is our goal to generate convenience methods for these, or is the expectation that they will continue to be protocol-only?

**Comment by lirenhe** [comment] 2023-06-20 09:47
> Thank you for these, @lirenhe!
> 
> Since DynamicData has released, I'd like to start sketching out this design now. It would be good for me to get a holistic understanding of how PATCH operations show up in our generated libraries.
> 
> * Are these two libraries - Azure.AI.ContentSafety and Azure.Developer.LoadTesting the only two we're currently tracking that have PATCH operations, or are there others?
> * Are they primarily used for CreateOrUpdate operations, or do they show up in any other ways?
> * Is our goal to generate convenience methods for these, or is the expectation that they will continue to be protocol-only?

Thanks @annelo-msft  to follow up on this.

1. Yes, those are the 2 libraries we found that use PATCH operations.  I am not aware of other service using this now.

2. As I know, they are used only in CreateOrUpdate operations, so I think we could just support 'application/merge-patch+json'.
   Not sure whether we should also support 'application/json-patch+json' today.  @m-nash?

3. Our goal is to generate convenience methods for PATCH operation.   Today, we asked service team to use protocol and do not do any customization mainly because we don't know how the convenience method would look like.

**Comment by mikekistler** [comment] 2023-06-20 12:49
The API Stewardship Board discourages 'application/json-patch+json'. There are some teams that support it so it should be "possible" but not "easy" -- so that teams must make a conscious choice to use it.

+1 on convenience methods for PATCH.

**Comment by pshao25** [comment] 2023-07-31 05:10
Scenario 1: normal patch operation with all the properties from required to optional
```
model Test {
  required: string;
  optional?: string;
}
@patch op method(@body body: Test): void;
```
Expected: we could send any combination of properties like:
```C#
var test = new Test();
test.Optional = "a"; // Not set required property
var response = someClass.Method(test);
```

Scenario 2: Same model in different places
```
model Test {
  required: string;
  optional?: string;
}
@patch op patch(@body body: Test): Test;
@post op post(@body body: Test): void;
```
```C#
var response = someClass.patch(new Test() {Optional = "a“}); // if return `{optional: "b"}` should fail because it should contain `required`
var response = someClass.post(new Test() {Optional = "a“}); // Should fail because it should contain `required`
```

**Comment by annelo-msft** [comment] 2023-07-31 15:41
Thanks for this use-case, @pshao25!  Can you help me understand what a corresponding API is in an existing service library?  It will help me understand the use case better if I can understand where a service is using this.

**Comment by annelo-msft** [comment] 2023-08-01 17:24
That is a great example, thank you @pshao25!  I will try to get back to you soon with a proposal for how we can address it.

**Comment by annelo-msft** [comment] 2023-08-02 23:34
Hi @pshao25, I have a clarifying question - I am looking at the model definition for `TextBlocklist` in the models file here: https://github.com/Azure/azure-rest-api-specs/blob/14d24d17491d8c2bde24532cb8cc2d663c0ffd9f/specification/cognitiveservices/ContentSafety/models.tsp#L134-L147

How can you tell that a property of the model is required for GET and not for PATCH?

From their [REST API documents](https://westus.dev.cognitive.microsoft.com/docs/services/content-safety-service-2023-04-30-preview/operations/TextBlocklists_CreateOrUpdateTextBlocklist), it looks like `blocklistName` is needed by URI, so should be taken by the model constructor to create the request, but not be written to the body by the serialize operation.  Specifically, I am suggesting that the client's service methods would have the following signatures:

```csharp
public virtual Response<TextBlocklist> CreateOrUpdateTextBlocklist(TextBlocklist blocklist, CancellationToken cancellationToken = default);
public virtual Response CreateOrUpdateTextBlocklist(string blocklistName, RequestContent content, RequestContext context = null);
public virtual Task<Response<TextBlocklist>> CreateOrUpdateTextBlocklistAsync(TextBlocklist blocklist, CancellationToken cancellationToken = default);
public virtual Task<Response> CreateOrUpdateTextBlocklistAsync(string blocklistName, RequestContent content, RequestContext context = null);
```

Do you know if there are any cases where we have required properties that aren't used in the URI?

**Comment by pshao25** [comment] 2023-08-03 13:39
@annelo-msft I'm not sure if that is the correct signature. I'm contacting typespec team to figure out some expected behavior about this scenario. Anyway the signature is not my emphasis in this issue.

> How can you tell that a property of the model is required for GET and not for PATCH?

Because when a model is used in a PATCH operation, all of its properties automatically become optional, right? You could set any part of them and leave any required property unset. That is PATCH!

> Do you know if there are any cases where we have required properties that aren't used in the URI?

I haven't find one. Once I got one, I'll let you know. But I believe it is very easy to understand this case. For example, 
```
@doc("Text Blocklist.")
@resource("text/blocklists")
model TextBlocklist {
  @key("blocklistName")
  blocklistName: string;
  description?: string;
  count: int;
}
createOrUpdateTextBlocklist is ResourceCreateOrUpdate<TextBlocklist>;
```
The added `count` could leave empty in a PATCH body like `{"description": "d"}` so that only description is updated. Could you update your example with this "though made up, very common I think" model?

And I just realized in this case we cannot set `count` to null because a required property cannot be deleted.

**Comment by chunyu3** [comment] 2023-09-21 09:12
duplicate with https://github.com/Azure/autorest.csharp/issues/3648

**Comment by pshao25** [comment] 2024-05-09 03:13
We will track in #3648

**Closed by pshao25** 2024-05-09 03:13 UTC
Labels: v3, Client, DPG, Epic: Model Generation, WS: Code Generation, DPG/RLC v2.1, GA-Required, Can-Customize
