### ISSUE TITLE
Implement TCGC's SdkPackage types

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.csharp#4534] opened 2024-04-04 17:32 UTC
Language emitters should work to move entirely to TCGC's new ecosystem. The entry point for the ecosystem is accessing .sdkPackage on the SdkContext returned from tcgc
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4747
```

**Comment by archerzz** [comment] 2024-04-08 08:18
I believe this is actually a duplicate of #3994

**Comment by archerzz** [comment] 2024-07-31 07:45
close since it's resolved in #4300

**Closed by archerzz** 2024-07-31 07:45 UTC
Labels: duplicate, DPG
