### ISSUE TITLE
prepend-rp-prefix behavior has changed

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#3908] opened 2023-11-06 16:36 UTC
The bahavior of `prepend-rp-prefix` has changed. It no longer takes the last word after the last dot for the RP Name. For `<RootNamespace>Azure.ResourceManager.Aaa.Bbb.Avs</RootNamespace>` it used to calculate `Avs` as the RP prefix. Now it calculates `AaaBbbAvs` as the RP prefix.

![image](https://github.com/Azure/autorest.csharp/assets/87583576/42aeb832-2221-423f-bb6e-7617697c8457)

Is there a way for me to get back the previous behavior? Or is there a way for me to explicitly set the RP prefix as `Avs` in the csproj or autorest.md`?

**Comment by cataggar** [comment] 2023-11-06 16:41
I'm not sure what is causing this change.  The line `MgmtContext.Context.DefaultNamespace.Split('.').Last()` looks like it should result in `Avs` as the prefix.

https://github.com/Azure/autorest.csharp/blob/7ec42556b6515821f1f1f02b654c98b583a1cf61/src/AutoRest.CSharp/Mgmt/Decorator/Transformer/CommonSingleWordModels.cs#L43-L56

**Comment by cataggar** [comment] 2023-11-06 17:31
This broke when we upgraded from `3.0.0-beta.20230531.2` to `3.0.0-beta.20230804.1`.  It looks like it was caused by

- #3470

cc @ArcturusZhang @m-nash

How do I get the prefix to be just `Avs` like before?

**Comment by cataggar** [comment] 2023-11-06 17:37
The use case is that we generating test clients for different API versions. The are in different C# projects and different C# namespaces.

- Azure.ResourceManager.v2023_03_01.Avs.csproj
- Azure.ResourceManager.v2023_09_01.Avs.csproj

Before `Avs` was the prefix. With the #3470 change, `V20230901Avs` is the prefix, which is what I want.

**Comment by ArcturusZhang** [comment] 2023-11-07 06:15
This is by design, we made this change because we need to ensure as much as possible that types in different namespaces to have different names.
There are two RPs `Azure.ResourceManager.PostgreSql.FlexibleServers` and `Azure.ResourceManager.MySql.FlexibleServers` which contains very similar models therefore we have to change the logic to take everything after Azure.ResourceManager to make sure there model factory could have a different name.

**Comment by cataggar** [comment] 2023-11-07 14:48
I understand, but that breaks our use case. A safer alternative would have been a way to configure the name and then configure the name for those RPs. Now, adding a way to configure it would also be a solution to unbreak my use case. Can you point me to the code for this logic? Is it different just for `Azure.ResourceManager`?

**Comment by ArcturusZhang** [comment] 2023-11-08 05:50
> I understand, but that breaks our use case. A safer alternative would have been a way to configure the name and then configure the name for those RPs. Now, adding a way to configure it would also be a solution to unbreak my use case. Can you point me to the code for this logic? Is it different just for `Azure.ResourceManager`?

You could use the `rename-mapping` functionality to rename a thing to whatever you want. You could find some document around this here: https://github.com/Azure/autorest.csharp/blob/73514b6dde9b060462c2b82c82ba8bbf2d5d1a70/docs/mgmt/polishing.md#rename-a-type

**Comment by cataggar** [comment] 2023-11-08 23:47
@ArcturusZhang, that workaround  only appears to work for models. There are several other files impacted including the model factory and these:

![image](https://github.com/Azure/autorest.csharp/assets/87583576/f6430271-e577-4818-a2e1-0a9eafc76be5)

**Comment by ArcturusZhang** [comment] 2023-11-13 05:44
> @ArcturusZhang, that workaround only appears to work for models. There are several other files impacted including the model factory and these:
> 
> ![image](https://user-images.githubusercontent.com/87583576/281572561-f6430271-e577-4818-a2e1-0a9eafc76be5.png)

Oh - for these, you could use customization code to add something like:
```csharp
[CodeGenType("ThePreviousGeneratedName")] // for instance you could `v2023_03_01AvsExtensions` here
public partial class YourNewName
{} // it does not need to contain anything inside this partial class
```

**Comment by ArthurMa1978** [comment] 2024-12-26 07:38
I'm closing this issue since it's by design change and provide mitigation plan.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Closed by ArthurMa1978** 2024-12-26 07:38 UTC
Labels: v3, Mgmt
