### ISSUE TITLE
[Bug] Typespec "bytes" request body is being treated like JSON

### ISSUE THREAD

**Issue by m-redding** [Azure/autorest.csharp#3963] opened 2023-11-21 21:24 UTC
**Describe the issue or request**
I'm working on switching over .NET Schema Registry from swagger to Typespec. I'm running into an issue where the generator is [writing code that assumes the request body is JSON](https://github.com/Azure/azure-sdk-for-net/blob/3750ec0bafaa57458b4aad037f77afae3b2695b1/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/Generated/SchemaRegistryClient.cs#L439) and serializing it, but I want it to be [treated as a stream or binary data](https://github.com/Azure/azure-sdk-for-net/pull/40141/files#r1399773975), etc since we allow custom schemas which could be as simple as just a string "Hello". This causes test failures because the serializer being used to create the request content throws a parsing error because the body is not in JSON format.

Right now, the [Typespec](https://github.com/Azure/azure-rest-api-specs/pull/25168/files#diff-1b5581b266947b270ea1249cc8c8763c9fc4a7e24b6e01182d84f07241795ee8) I am generating from is specifying that the response body is bytes. After an offline discussion, it was decided that the expectation in this case is that the csharp emitter should keep the payload as bytes.

Previously, we were having similar issues with swagger and needed to use transforms to [change the array](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/autorest.md#update-producers-arrays---get-version). I'm not sure if something along the same lines could be going wrong here.

No known workaround at this time, I tried changing `bytes` to `unknown` which didn't fix the issue.

**Comment by pshao25** [comment] 2023-12-04 06:16
@m-redding could you clarify the issue happens for request body or response body? The [link](https://github.com/Azure/azure-sdk-for-net/blob/3750ec0bafaa57458b4aad037f77afae3b2695b1/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/Generated/SchemaRegistryClient.cs#L439) you provided is for request body. The problem is fixed in the latest version.

**Comment by m-redding** [comment] 2023-12-08 17:31
I just updated this [branch](https://github.com/m-redding/azure-sdk-for-net/tree/sr-tsp-4) and I'm not seeing any changes. : Is `20231207.1` available in the . NET repo yet? The most recent update I see is `20231206.2`  https://github.com/Azure/azure-sdk-for-net/pull/40622

**Comment by pshao25** [comment] 2023-12-11 10:01
@m-redding Your branch is already updated to 20231207.1. Your issue comes from your definition of content-type. This is what I see in spec:
```
union SchemaContentTypeValues {
  avro: "application/json; serialization=Avro",
  @added(ServiceApiVersions.V2022_10)
  json: "application/json; serialization=json",
  @added(ServiceApiVersions.V2022_10)
  custom: "text/plain; charset=utf-8",
  @added(ServiceApiVersions.V2023_07_01)
  protobuf: "text/vnd.ms.protobuf",
}
```
Currently we only take the first one if there are multiple. So, you are telling generator your content type is "application/json", and generator gives `RequestContentHelper.FromObject`. 

Generator only gives `RequestContent.Create` only when your content-type is binary type, e.g, "application/octet-stream". I think none of your 4 content types falls into the binary category. Therefore we won't generate `RequestContent.Create` even later we support multiple case.

**Comment by m-redding** [comment] 2023-12-11 15:46
@pshao25 Thank you for looking into this and for the information. This is helpful to know. I think we ran into something similar with swagger since we had to have the following transform, since having the text/ types caused a similar issue:
```yaml
directive:
  from: swagger-document
  where: $.paths["/$schemaGroups/{groupName}/schemas/{schemaName}/versions/{schemaVersion}"].get
  transform: >
    $.produces = [
        "application/json; serialization=Avro",
        "application/json; serialization=json",
        "application/octet-stream"
    ]
```

I'll see if we can figure out a workaround for this scenario, maybe we can trying changing the content type to applciation/octet-stream for csharp.

**Comment by pshao25** [comment] 2023-12-12 02:57
@m-redding 
1. For this request scenario, I'm afraid you don't have workaround. It is expected that content-type should be binary type. `application/octet-stream` is just an example, image, video, audio are also binary type.
2. The directives you provided is for response scenario. Do you have problem for response as well? Do you have specific example?
3. In Typespec world, directives don't take any effect.

**Comment by m-redding** [comment] 2024-01-10 21:23
@pshao25 sorry for the delayed response I just realized I hadn't posted my solution here. We don't currently have an issue with the response scenario, but it was essentially the exact same problem where we couldn't get the output to be treated as bytes.

I was able to work around this issue by changing the Schema content type values:

Before:
```
union SchemaContentTypeValues {
  avro: "application/json; serialization=Avro",
  @added(ServiceApiVersions.V2022_10)
  json: "application/json; serialization=json",
  @added(ServiceApiVersions.V2022_10)
  custom: "text/plain; charset=utf-8",
  @added(ServiceApiVersions.V2023_07_01)
  protobuf: "text/vnd.ms.protobuf",
}
```
After:
```
union SchemaContentTypeValues {
  @added(ServiceApiVersions.V2022_10)
  custom: "application/octet-stream",
  avro: "application/json; serialization=Avro",
  @added(ServiceApiVersions.V2022_10)
  json: "application/json; serialization=json",
  @added(ServiceApiVersions.V2023_07_01)
  protobuf: "text/vnd.ms.protobuf",
}
```

We don't use the content type in our code anywhere, it is only used by the generator, so this is a sufficient workaround for us. Thank you for your help!

**Comment by m-redding** [comment] 2024-02-13 21:59
@pshao25 Happy New Year! After getting a review on the spec I was told that the workaround I shared above wasn't acceptable from a Typespec perspective. Do you happen to know if there's anything else that I could do to get around this?

**Comment by pshao25** [comment] 2024-02-19 06:45
Are you saying you cannot change order of `union SchemaContentTypeValues`? I didn't quite understand your expectation. You defined your body as `bytes`, but your content type has both `json` type and binary type. We can generate binary type for binary content type, but we cannot generate binary type for `json` content type. Could you elaborate more?

**Comment by pshao25** [comment] 2024-02-19 06:48
And I would suggest you create a new issue to describing current issue, there are too many ones in this single issue.

**Closed** 2024-06-11 02:33 UTC
Labels: v3, workaround-hard, needs-author-feedback, no-recent-activity, DPG, DPG/RLC v2.1
