### ISSUE TITLE
generator doesn't respect namespace specified in readme.csharp.md

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#604] opened 2020-04-01 02:18 UTC
If we don't specify --namespace parameter during running autorest csharp generator, it doesn't respect namespace specified in readme.csharp.md, e.g. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/readme.csharp.md, it generates code with namespace **Sample**

**Comment by pakrym** [comment] 2020-04-01 03:07
You are not supposed to be running autorest directly, the GenerateCode target would take care of the namespace.

**Comment by pakrym** [comment] 2020-04-22 23:20
Closing by design.

**Closed by pakrym** 2020-04-22 23:20 UTC
Labels: v3
