### ISSUE TITLE
Convert schema operations into input operations for MPG

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#3772] opened 2023-09-22 16:09 UTC
After https://github.com/Azure/autorest.csharp/issues/3768 and https://github.com/Azure/autorest.csharp/issues/3770, add conversion of schema operations into input operations for MgmtTarget, so that all MPG-specific types are generated from `InputNamespace` rather than `CodeModel`.
This will finalize the consolidation of internal surface of codegen (rest clients + models).

**Comment by m-nash** [comment] 2024-03-26 21:29
@AlexanderSher  can you assign this to an iteration or close if it is a duplicate of work @live1206 is doing?

**Comment by ArthurMa1978** [comment] 2024-05-21 02:31
Tracked by https://github.com/Azure/autorest.csharp/issues/4415

**Closed by ArthurMa1978** 2024-05-21 02:31 UTC
Labels: v3
