### ISSUE TITLE
Conflicting enums are instead combined

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#583] opened 2020-03-27 00:00 UTC
In searchindex.json and searchservice.json, both define a `SearchMode` enum. In the former, it has two values: "any" and "all". In the latter, only one: "analyzeInfixMatching". In the latter case, it should just be hardcoded to `Suggester` but is not, and instead is merged with the `SearchMode` enum.

**Comment by heaths** [comment] 2020-03-27 00:36
I was almost able to workaround this by using `CodeGenSchemaAttribute` to define a new enum with just the 2 values. I declared a string property on the model. However, the serialization code still references the type. I'll have to use autorest.md to rename it.

**Comment by pakrym** [comment] 2020-03-29 14:49
They both define the same `"x-ms-enum": {name": "searchMode"}` this is the intended behavior. The only other option is to produce an error but in both cases swagger change or readme transform would be required.

**Comment by heaths** [comment] 2020-03-30 17:04
And is probably one reason we won't be able to combine these two files (/cc @tg-msft @brjohnstmsft). We could possibly rename one, but it really depends on how other generators (our older ones or third-party ones would react). I imagine that this would be considered a breaking change, even though, IIRC, our v2 and our v3 (for sure) generators treat a single-valued enum as a constant/default value. Could that be true of any generators? Probably not.

Fortunately, if I use our autorest.md file to rename the `x-ms-enum` value the right thing happen (value treated as a constant, no enum generated for this instance, and the other enum has only the 2 values expected). Maybe this is an isolated case.

**Comment by pakrym** [comment] 2020-04-10 18:54
I'm closing this as a Swagger issue but feel free to reopen if you think there is something you think we can do in the generator.

**Closed by pakrym** 2020-04-10 18:54 UTC
Labels: v3

**Comment by heaths** [comment] 2020-04-10 19:08
Hopefully it's rare enough. Thanks for considering.

**Comment by brjohnstmsft** [comment] 2020-04-20 21:16
@heaths Should we fix this in the Swagger? For example, we can rename one of the `SearchMode`s to `SuggesterSearchMode`.

**Comment by heaths** [comment] 2020-04-20 23:31
Would that be considered a breaking change, though? Especially since Search doesn't actually change the api-version (hasn't since 2018 anyway), while our generators treat single-valued enums as constants, that may not be universal. I'm not sure how much that matters, though.

But, yes, if not a valid concern, that would be good to change in the swagger. I know @sima-zhu would prefer that as well, and it should then make it possible to combine swaggers if that's still a desire.

**Comment by brjohnstmsft** [comment] 2020-04-21 00:39
We've never shipped a GA Track 2 library, so as far as the 2019-05-06-Preview spec is concerned, there are no breaking changes.

https://github.com/Azure/azure-rest-api-specs/issues/9148

**Comment by heaths** [comment] 2020-04-21 00:41
I meant breaking from a REST/swagger perspective. Surely other people use this method, yes?

**Comment by brjohnstmsft** [comment] 2020-04-21 00:45
We're talking about renaming an enum type. Those have no real existence on the server side, and only the in-progress Track 2 libraries are using the latest Swagger, so this change should have zero impact.

**Comment by heaths** [comment] 2020-04-21 00:50
Sorry, yes. I forgot we were talking about the x-ms-enum property, which is Microsoft-speicfic, of course, and not the model name itself (which, yes, doesn't matter in JSON but other generators might use it). That said, while we could change the x-ms-enum, we'll still have a model name conflict preventing merging the docs together.
