### ISSUE TITLE
Need to generate SDKs with both LLCs and convenience wrappers

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#1338] opened 2021-06-21 22:38 UTC
For QnA Maker - though I suspect this may become more common with the push to LLCs - we need to generate a single SDK with LLCs for the authoring side of the APIs (conveniently in another file, if that helps) but convenience wrappers for the inference side of the APIs along with related models.

This currently does not seem possible, nor does the `batch` directive for autorest seem to work completely.

**Comment by chamons** [comment] 2021-06-22 20:10
Duplicate of https://github.com/Azure/autorest.csharp/issues/1137

**Closed by chamons** 2021-06-22 20:10 UTC
Labels: v3, workaround-hard
