### ISSUE TITLE
Enum values are being dropped from response object after using deserialization methods.

### ISSUE THREAD

**Issue by alec-baird** [Azure/autorest.csharp#4365] opened 2024-03-07 17:14 UTC
**Describe the issue or request**
When using the SDK generated by autorest to craft our response objects, enums have their values dropped after sending the response object over the wire. This is an example of an ARMClient call made with our old handcrafted response objects that successfully return enums:
![ARMClient_oldResponse](https://github.com/Azure/autorest.csharp/assets/100880612/0cffb448-0124-4650-bb32-e58bde28eeec)

ARMClient response when using the SDK deserialization method, resulting in the enum values being removed:
![ARMClient_newResponse](https://github.com/Azure/autorest.csharp/assets/100880612/8d0f0ac8-f26d-419e-8469-7592c34c7e3e)

**Comment by chunyu3** [comment] 2024-03-08 01:38
Hello @alec-baird Would you please provide the api spec (swagger or typespec) file you use and what's the property value who missing value? Are the sdk management-plane or data-plane?

Thanks

**Comment by alec-baird** [comment] 2024-03-08 01:49
We are using this swagger API spec, and any enum that is a Workspace Property (PublicNetworkAccess is an example, but we have the same issue with the SystemData enums). We are management-plane: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/stable/2023-09-05/desktopvirtualization.json

**Comment by live1206** [comment] 2024-03-08 06:02
@alec-baird 
> The odd behavior is when we use the SDK deserialization method, it returns the enum as "{value}", instead of "value"

I don't quite understand how you use the SKD deserialization method. As I can see from the [changelog](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/CHANGELOG.md), desktopvirtualization SDK has been updated to use the new serialization, but not released yet.
![image](https://github.com/Azure/autorest.csharp/assets/5196139/d85da0ee-81c4-496e-a7e9-50bf78d194b9)

From the description of this issue, I don't see what's going on under the command-line execution.
Could you create a scenario test under [this folder](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/tests/Scenario) and share with me your working branch or even better to create a draft PR to demonstrate the issue? So that, it would be easier for me to reproduce the issue. Thanks!

**Comment by live1206** [comment] 2024-03-08 07:34
As offline synced, the user would like to use the SDK generated models as server side models.
The issue of the serialization round trip is, let's say `PublicNetworkAccess` is deserialized into a c# Enum.
But service handler is using system.text.json to serialize it and the SDK model doesn't specify `PublicNetworkAccess` should be serialized as string. That's why it ends up into `{Enabled}`.
There will be some manual tweaking on the models from SDK generation to make the serialization round trip work.

Close this for now since we clarifies the root cause.

**Closed by live1206** 2024-03-08 07:34 UTC
Labels: v3, EngSys, blocking-release, customer-reported, CodeGen
