### ISSUE TITLE
Improve the retry mechanism in LRO method

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1926] opened 2022-01-27 07:20 UTC
Currently the retry interval is fixed 1s which is bad, should get the interval time from the service response

**Comment by archerzz** [comment] 2022-03-09 01:40
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/26922

**Closed by archerzz** 2022-03-09 01:40 UTC
Labels: Mgmt, duplicate
