### ISSUE TITLE
Omit "gets or sets"

### ISSUE THREAD

**Issue by deastr** [Azure/autorest.csharp#903] opened 2020-09-21 14:06 UTC
Is it possible to have an option to omit "gets or sets" text from model properties? Our documentation is not in English so having "gets or sets" text with them looks weird.

**Comment by chamons** [comment] 2021-05-27 15:16
From what I can tell, the only code generated with the text "gets or sets" is https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Mgmt/Generation/ResourceWriter.cs#L47 (There are 2 usages in CodeGenModelAttribute which is shared code and one internal to autorest.csharp).

That makes this a Mgmt bug - FYI @m-nash

**Comment by ArthurMa1978** [comment] 2021-12-14 03:47
@deastr could you help to provide more information or samples?

**Comment by deastr** [comment] 2021-12-17 18:58
I haven't worked with AutoRest for a while but AFAIK it was something like this: if your properties are non-English they look like "Gets<non-English-word>" when  they are generated. I was asking if it's possible to generate without the Gets/Sets prefix.

**Comment by ArthurMa1978** [comment] 2023-04-18 07:25
The AutoRest is not intended to handle globalized text, and we expect that property / variable names will be in English.
So close this issue as by design.

**Closed by ArthurMa1978** 2023-04-18 07:25 UTC
Labels: v3, Mgmt, needs-team-attention, customer-reported
