### ISSUE TITLE
We should not use the boolean value of 'branded' to decide branding/non-branding

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#4071] opened 2023-12-25 06:18 UTC
Today, we are using the following option to decide whether to do branding or not:

```
public const string Branded = "branded";
```

Based on the requirement, we should use the branding value that the user of the generator inputs.
so we need to update the implementation of the handling of Branded in csharp code.

**Comment by archerzz** [comment] 2024-03-11 06:34
close since it's a duplicate of #4309

**Closed by archerzz** 2024-03-11 06:34 UTC
Labels: v3, DPG, DPG/RLC v2.1, GA-Required, feature
