### ISSUE TITLE
Implement resilient model generation for changes allowed by the Azure Breaking Change rules

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2355] opened 2022-06-21 18:59 UTC
See http://aka.ms/AzBreakingChangesPolicy

This issue tracks implementation of the design described by https://github.com/Azure/autorest.csharp/issues/2351

[Description TBD]

**Comment by lirenhe** [comment] 2023-02-10 05:57
close this one as duplicate of https://github.com/Azure/autorest.csharp/issues/2351

**Closed by lirenhe** 2023-02-10 05:57 UTC
Labels: v3, Client, needs-design, DPG, DPG/RLC v2.0 GA, Epic: Model Generation, WS: Code Generation
