### ISSUE TITLE
Track 2 .NET SDK mgmt client should take `credentialScopes`

### ISSUE THREAD

**Issue by jiasli** [Azure/autorest.csharp#972] opened 2021-01-08 03:48 UTC
**Describe the issue or request**

Track 2 Python SDK mgmt client treats `base_url` (`endpoint` in .NET SDK) and `credential_scopes` separately:

https://github.com/Azure/azure-sdk-for-python/blob/27e4203818e227ba2604ff52dcf55ce2293c4c37/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L58-L63

```py
def __init__(
    ...
    base_url=None,
```

https://github.com/Azure/azure-sdk-for-python/blob/27e4203818e227ba2604ff52dcf55ce2293c4c37/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_configuration.py#L47

```py
self.credential_scopes = kwargs.pop('credential_scopes', ['https://management.azure.com/.default'])
```

Sometimes `base_url` and `credential_scopes` are different. The current Track 2 .NET SDK mgmt client uses `endpoint` as `scopes` when retrieving the token. 

https://github.com/Azure/azure-sdk-for-net/blob/05209aa50e9eab80197ef3dcf3433181e7d0934b/sdk/resources/Azure.ResourceManager.Resources/src/Generated/ResourcesManagementClient.cs#L41

```cs
public ResourcesManagementClient(Uri endpoint, string subscriptionId, TokenCredential tokenCredential, ResourcesManagementClientOptions options = null)
```

https://github.com/Azure/autorest.csharp/blob/7324ab32ee6ac757a7f81faa02472f389176edfd/src/assets/Generator.Shared/ManagementPipelineBuilder.cs#L19

This causes failure if `endpoint` is not a valid resource registered in AAD, making the test on Continuous Access Evaluation (CAE) impossible, as the `endpoint` differs from the resource ID in `scopes`:

- endpoint: `https://eastus2euap.management.azure.com/`
- scope: `https://management.azure.com/.default`

https://github.com/erich-wang/MsalTestApp/blob/900ac96e98a60f63e35d5e43a08add3afdf15c28/MsalTestApp/Program.cs#L103

```cs
var client = new ResourcesManagementClient(new Uri("https://eastus2euap.management.azure.com/"), "", sharedCredential, null);
```

**Describe your ideas for solutions**

- Track 2 .NET SDK mgmt client should take `credentialScopes` which is different as `endpoint`.
- It may be better if .NET SDK can rename `endpoint` to `baseUrl` to be in sync with Python SDK.

**Comment by jiasli** [comment] 2021-01-08 03:50
\+ @schaabs @lmazuel for awareness.

**Comment by lmazuel** [comment] 2021-01-08 17:38
@pakrym @ShivangiReja I think it's a fair ask, since all other SDK supports it already (we talked about that in scrum). Feel free to bring the topic in scrum if there is concerns,

**Comment by abatishchev** [comment] 2021-01-11 04:32
@lmazuel how's the .NET SDK supports this? I don't think the stable version does. See https://github.com/Azure/azure-sdk-for-net/issues/13603

**Comment by lmazuel** [comment] 2021-01-11 20:58
@abatishchev I think this is issue is precisely about the .NET SDK not supporting it yet :)

**Comment by abatishchev** [comment] 2021-01-11 21:52
Ah, sorry! Indeed, my bad. Got confused between the issues and platforms :)

**Comment by AlexGhiondea** [comment] 2021-05-21 18:20
This feature is supported already [here](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/DataPlane/Generation/DataPlaneClientWriter.cs#L156) for the data plane. Closing this issue for now.

**Closed by AlexGhiondea** 2021-05-21 18:20 UTC
Labels: v3

**Comment by jiasli** [comment] 2021-05-25 05:50
> This feature is supported already [here](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/DataPlane/Generation/DataPlaneClientWriter.cs#L156) for the data plane. Closing this issue for now.

Isn't mgmt plane still suffering from this issue? It makes using .NET SDK with dogfood, canary, Azure Stack impossible.

**Comment by abatishchev** [comment] 2021-05-25 21:15
@AlexGhiondea the issue is for Management/Control Plane. And you're closing the issue because it's already supported by Data Plane. Ok but why?
