### ISSUE TITLE
defect(cadl): usage of model is incorrect if it inherits a model

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#2882] opened 2022-11-24 13:14 UTC
## Problem

See this [input model](https://github.com/Azure/autorest.csharp/blob/05205d82be7a708200197aacccb439a58e0f030b/test/TestProjects/Models-Cadl/Models-Cadl.cadl#L156). If it extends `BaseModel`, then in the generated `cadl.json` its usage is `RoundTrip`.

**Comment by chunyu3** [comment] 2022-12-12 06:00
The root cause: resolveUsages() API apply the same usage for base and derived model.

I filed an issue for cadl for this https://github.com/microsoft/cadl/issues/1421

**Comment by chunyu3** [comment] 2023-02-08 05:41
Resolved. Close it.

**Closed by chunyu3** 2023-02-08 05:41 UTC
Labels: v3, Client, DPG, DPG/RLC v2.0 GA, Epic: Model Generation, WS: Code Generation
