### ISSUE TITLE
Operations not generated as expected from TypeSpec

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.csharp#3344] opened 2023-05-03 21:59 UTC
Opening this issue that the Content Safety team mentioned in teams:

TypeSpec link: https://github.com/Azure/azure-rest-api-specs-pr/pull/9275

For this [operation in typespec](https://github.com/Azure/azure-rest-api-specs-pr/blob/bdd03b95e0ccf52c3578fac731bc392734d2ea44/specification/cognitiveservices/ContentSafety/routes.tsp#L55):

```
 @summary("Create Or Update Text Blocklist")
  @doc("Updates a text blocklist, if blocklistName does not exist, create a new blocklist.")
  @convenientAPI
  createOrUpdateTextBlocklist is Azure.Core.ResourceCreateOrUpdate<TextBlocklist>;
```
Generated code has no overload to take both blocklistName and TextBlocklist(or description defined in TextBlocklist), only has following:
```
public virtual Response CreateOrUpdateTextBlocklist(string blocklistName, RequestContent content, RequestContext context = null)
```

@mengaims can provide more information on what is expected here.

**Comment by catalinaperalta** [comment] 2023-05-03 21:59
@m-nash any suggestions here would be appreciated

**Comment by catalinaperalta** [comment] 2023-05-03 22:00
Another operation that is not generated as expected:

```
public virtual Pageable<TextBlocklist> GetTextBlocklistItems(string blocklistName, int? maxCount = null, int? skip = null, int? maxpagesize = null, CancellationToken cancellationToken = default)
```

The corresponding typespec code is:

```
 @summary("Get All BlockItems By blocklistName")
  @doc("Get all blockItems in a text blocklist")
  listTextBlocklistItems is Azure.Core.ResourceList<
    TextBlockItem,
    ListQueryParametersTrait<StandardListQueryParameters>
  >;
```

**Comment by mengaims** [comment] 2023-05-04 08:57
> Opening this issue that the Content Safety team mentioned in teams:
> 
> For this operation in typespec:
> 
> ```
>  @summary("Create Or Update Text Blocklist")
>   @doc("Updates a text blocklist, if blocklistName does not exist, create a new blocklist.")
>   @convenientAPI
>   createOrUpdateTextBlocklist is Azure.Core.ResourceCreateOrUpdate<TextBlocklist>;
> ```
> 
> Generated code has no overload to take both blocklistName and TextBlocklist(or description defined in TextBlocklist), only has following:
> 
> ```
> public virtual Response CreateOrUpdateTextBlocklist(string blocklistName, RequestContent content, RequestContext context = null)
> ```
> 
> @mengaims can provide more information on what is expected here.

See my manual fix for the expected generation:
https://github.com/Azure/azure-sdk-for-net/pull/34933/commits/9825c373132944c546aed6840847e5914e99cd77

**Comment by mengaims** [comment] 2023-05-04 08:59
> Another operation that is not generated as expected:
> 
> This method should return TextBlockItem instead of TextBlocklist：
> 
> ```
> public virtual Pageable<TextBlocklist> GetTextBlocklistItems(string blocklistName, int? maxCount = null, int? skip = null, int? maxpagesize = null, CancellationToken cancellationToken = default)
> ```
> 
> The corresponding typespec code is:
> 
> ```
>  @summary("Get All BlockItems By blocklistName")
>   @doc("Get all blockItems in a text blocklist")
>   listTextBlocklistItems is Azure.Core.ResourceList<
>     TextBlockItem,
>     ListQueryParametersTrait<StandardListQueryParameters>
>   >;
> ```

The same, see may manual fix for the expected generation:
https://github.com/Azure/azure-sdk-for-net/pull/34933/commits/84919ede9ca3cbe759c01e6d6bf786f4c37365e4

**Comment by chunyu3** [comment] 2023-05-05 03:32
> Azure.Core.ResourceList<
>     TextBlockItem,
>     ListQueryParametersTrait<StandardListQue

as the tsp definition, the operation will take `blocklistName` as path parameter and model `TextBlocklist` as the body parameter,
So codegen will generate  following protocol method:
```
public virtual Response CreateOrUpdateTextBlocklist(string blocklistName, RequestContent content, RequestContext context = null)
```

If you enable to generate convenience method, codegen will generate convenience method
```
public virtual Response CreateOrUpdateTextBlocklist(string blocklistName, TextBlocklist content, CancellationToken cancellationToken = default)
```

So the operation generated is as expected according to the tsp definition.

**Comment by mengaims** [comment] 2023-05-05 13:57
> 

Thanks @chunyu3 for the update! I've checked [latest generated code](https://github.com/mengaims/azure-sdk-for-net/blob/carnegie-test/sdk/contentsafety/Azure.AI.ContentSafety/api/Azure.AI.ContentSafety.netstandard2.0.cs), only the first method is generated and the the second one was not, although I have convenient decorator in tsp:
`  @summary("Create Or Update Text Blocklist")
  @doc("Updates a text blocklist, if blocklistName does not exist, create a new blocklist.")
  @convenientAPI
  createOrUpdateTextBlocklist is Azure.Core.ResourceCreateOrUpdate<TextBlocklist>;`
Could you help have a check?

**Comment by pshao25** [comment] 2023-05-08 08:59
@catalinaperalta @mengaims 
`createOrUpdateTextBlocklist is Azure.Core.ResourceCreateOrUpdate<TextBlocklist>;` is a patch operation. So we don't generate convenience method. It is a known issue.

**Comment by mengaims** [comment] 2023-05-09 07:42
Add @heaths for awareness of these two issues.

**Comment by mengaims** [comment] 2023-05-09 13:54
@pshao25, how could sdk user initialize RequestContent if only this method is provided?
`public virtual Response CreateOrUpdateTextBlocklist(string blocklistName, RequestContent content, RequestContext context = null)`

**Comment by catalinaperalta** [comment] 2023-05-09 17:08
> > 
> 
> Thanks @chunyu3 for the update! I've checked [latest generated code](https://github.com/mengaims/azure-sdk-for-net/blob/carnegie-test/sdk/contentsafety/Azure.AI.ContentSafety/api/Azure.AI.ContentSafety.netstandard2.0.cs), only the first method is generated and the the second one was not, although I have convenient decorator in tsp: ` @summary("Create Or Update Text Blocklist") @doc("Updates a text blocklist, if blocklistName does not exist, create a new blocklist.") @convenientAPI createOrUpdateTextBlocklist is Azure.Core.ResourceCreateOrUpdate<TextBlocklist>;` Could you help have a check?

Did your generation improve after removing @convenientAPI?

**Comment by chunyu3** [comment] 2023-05-10 03:42
> Did your generation improve after removing @convenientAP

As @pshao25 said, this is patch operation, and now we will not auto-gen convenience method for patch operation. 
we plan to support this in future, and  I will discuss with our arch about the schedule. Thanks.

**Comment by pshao25** [comment] 2023-05-10 09:44
@mengaims There are sample docs generated in the Docs folder right near the generated code. You could take it as a reference.

**Comment by mengaims** [comment] 2023-05-10 13:32
> > > 
> > 
> > 
> > Thanks @chunyu3 for the update! I've checked [latest generated code](https://github.com/mengaims/azure-sdk-for-net/blob/carnegie-test/sdk/contentsafety/Azure.AI.ContentSafety/api/Azure.AI.ContentSafety.netstandard2.0.cs), only the first method is generated and the the second one was not, although I have convenient decorator in tsp: ` @summary("Create Or Update Text Blocklist") @doc("Updates a text blocklist, if blocklistName does not exist, create a new blocklist.") @convenientAPI createOrUpdateTextBlocklist is Azure.Core.ResourceCreateOrUpdate<TextBlocklist>;` Could you help have a check?
> 
> Did your generation improve after removing @convenientAPI?

@catalinaperalta The convenientAPI is not the root cause of it, I've tried the typespec without this decorator and things are the same. As Crystal mentioned, this is expected behavior of the generation tool now. But I think from the service point of view, we would need a better method for customer to use. And I will continue this discussion to get knowledge about how to customize it or if manual work is required here.

**Comment by chunyu3** [comment] 2023-05-11 01:43
File a sperate issue https://github.com/Azure/autorest.csharp/issues/3386 for incorrect list operation issue.

**Comment by pshao25** [comment] 2023-05-11 06:14
`createOrUpdateTextBlocklist is Azure.Core.ResourceCreateOrUpdate<TextBlocklist>;` is a patch operation. We will not implement convenience method until Mid June.

`listTextBlocklistItems is Azure.Core.ResourceList<TextBlockItem, ListQueryParametersTrait<StandardListQueryParameters>>; ` is tracked at https://github.com/Azure/autorest.csharp/issues/3386

So close this.

**Closed by pshao25** 2023-05-11 06:14 UTC
Labels: v3, DPG
