### ISSUE TITLE
Generator needs to automatically add suppresion for AZC0014 if JsonElement is used in tsp

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3709] opened 2023-09-01 21:34 UTC
Current `Customizations-TypeSpec` project fails for this reason and is temporarily suppressed.

**Comment by archerzz** [comment] 2023-10-23 07:11
The root cause is the customization codes which change the type from `string` to `JsonElement`: https://github.com/Azure/autorest.csharp/blob/12c70bbb980316bbfe0b0da34f19bc9fd7ba1bce/test/TestProjects/Customizations-TypeSpec/src/Customizations/ModelWithCustomizedProperties.cs#L47
Tsp definition is `string`: https://github.com/Azure/autorest.csharp/blob/12c70bbb980316bbfe0b0da34f19bc9fd7ba1bce/test/TestProjects/Customizations-TypeSpec/Customizations-TypeSpec.tsp#L77

---

There are a few ways to suppress this warning.
- Inline suppression using `#pragma` or `[SuppressMessage]`:
  - precise
  - most complex logic since we need to locate the exact lines of codes to suppress
  - have to modify `Customize` codes which is not a good idea
- `<NoWarn>` in `csproj` file
- `.editorconfig` or `XXX.Build.Props` or `.analyzerconfig`: those files are definitely out of scope of generator

So, looks like modifying `csproj` is the way to go

**Comment by archerzz** [comment] 2023-10-23 08:45
@m-nash We've discussed this issue, and we recommend just close it as is. Because:

- `JsonElement` is not specified in tsp, it's specified by custom codes.
- To suppress in codes, we need to suppress in both generated codes and custom codes. We feel it's not comfortable to modify custom codes.
  - If we only suppress in generated codes and expect users to suppress in custom codes, the whole experience looks weird.
- Modifying `csproje` or `.editorconfig` or `XXX.Build.Props` is quite out of the scope of generator.

Considering it's a low-probability case, we thought it might be OK to just let users to suppress it.

**Closed** 2023-11-29 09:11 UTC
Labels: v3, DPG, DPG/RLC v2.1
