### ISSUE TITLE
Optional integer parameter with non-null default value generates incorrect signature

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2261] opened 2022-05-27 08:49 UTC
Use this swagger:
```
{
  "name": "optionalInt",
  "in": "query",
  "description": "I'm a new input optional parameter",
  "type": "integer",
  "x-ms-client-default": "7"
}
```
Actual behavior:
```C#
public virtual async Task<Response> PutRequiredOptionalAsync(int? optionalInt = 7, RequestContext context = null);
```
Expected behavior: the parameter has default value 7, but it is not nullable. It should not have signature `int?`.

**Comment by lirenhe** [comment] 2022-05-27 09:25
cc @annelo-msft

**Comment by AlexanderSher** [comment] 2022-05-31 20:06
All header and query parameters are considered optional not in a sense of C# method signature, but in a sense of request construction: header or query value may not be presented in request at all. Hence `null` is a valid input that will be handled in `CreateXXXRequest` method:
```cs
if (optionalInt != null)
{
    uri.AppendQuery("optionalInt", optionalInt.Value, true);
}
```

`x-ms-client-default` is a hint for the client that shouldn't interfere with what is allowed by protocol.

**Comment by annelo-msft** [comment] 2022-05-31 20:19
@pshao25, why is this marked blocking release?

**Comment by AlexanderSher** [comment] 2022-05-31 20:23
In fact, `x-ms-client-default` may not be the value that is used by service when client provides no value. For example, default value for `maxItemsPerPage` may be `20`, meaning that we suggest returning 20 items per page. But omitting `maxItemsPerPage` from the query would mean for the service to return all items at once.

**Comment by annelo-msft** [comment] 2022-05-31 20:28
> But omitting `maxItemsPerPage` from the query would mean for the service to return all items at once.

Unless the service had its own default value for `maxItemsPerPage`, correct?

**Comment by annelo-msft** [comment] 2022-05-31 20:30
@mikekistler, @lmazuel FYI

**Comment by annelo-msft** [comment] 2022-05-31 23:36
Closing as "by design"

**Comment by pshao25** [comment] 2022-06-01 04:35
@mikekistler we have such case in test server https://github.com/Azure/autorest.testserver/blob/main/swagger/constants.json#L42-L53
It is an enum optional value type, and has `x-ms-client-default` value.
But in SDK repo, I haven't find one.

**Comment by mikekistler** [comment] 2022-06-01 20:08
To be clear, I am not suggesting client-side validation -- I am suggesting validation of the REST API definition. I am proposing that the generator should fail when it finds an optional parameter that specifies `x-ms-client-default`.

What could be the justification for our clients to use a _different_ default than the one defined by the service? This seems completely contrary to the notion that DPG methods are "protocol" methods.

**Comment by mikekistler** [comment] 2022-06-01 20:13
BTW ... I just checked the azure-rest-api-specs repo and found no instances of optional parameters that specify an `x-ms-client-default`.

**Comment by chunyu3** [comment] 2023-08-23 08:46
Not support client-default-value, close it.

**Closed by chunyu3** 2023-08-23 08:46 UTC
Labels: v3, DPG, WS: Code Generation
