### ISSUE TITLE
How to add set Property in the generated models files using autorest

### ISSUE THREAD

**Issue by KotanaSai21** [Azure/autorest.csharp#4294] opened 2024-02-16 11:01 UTC
Working on C# SDK and able to generate the client files and models using the autorest v3. Here is my [GitHub Repo](https://github.com/KotanaSai21/PowerBI-CSharp/tree/master/sdk).

Now the issue is with generated models file. For instance in this generated model [file ](https://github.com/KotanaSai21/PowerBI-CSharp/blob/02e2cff36f16de8a6f990108d7a3d9d0cfde4c91/sdk/PowerBI.Api/Source/Models/EffectiveIdentity.cs#L54C8-L54C47) datasets cannot be set. 

But in the old generated models [file](https://github.com/microsoft/PowerBI-CSharp/blob/ab2a810a4f8326e0c23235ce31c7f83ab18ebe18/sdk/PowerBI.Api/Source/Models/EffectiveIdentity.cs#L106), dataset property can also be set.

Snapshot of generated model file in the old file using autorest v2:
<img width="400" alt="image" src="https://github.com/Azure/autorest/assets/47911842/227e5768-8c33-462a-851b-c45bffd619cf">

Snapshot of generated model file using autorestv3
<img width="223" alt="image" src="https://github.com/Azure/autorest/assets/47911842/fd60a4b3-a1b1-4cf1-badd-b70e663aaa69">

I want the property set also be added in my generated model's file. How to achieve that? Checked the swagger file if there is any difference between auditableContext and dataset, As for auditableContext set is added for dataset it's not. 
Here is my swagger json [file](https://github.com/KotanaSai21/PowerBI-CSharp/blob/02e2cff36f16de8a6f990108d7a3d9d0cfde4c91/sdk/swaggers/swagger.json#L27226C8-L27261C19).

Could you please help me. Please do let me know if any additional details required.

**Comment by ArcturusZhang** [comment] 2024-04-07 03:05
Hi @KotanaSai21 sorry for the delay of response.
It is by design that generated collection properties do not have setters.
For mutable lists, the type is generated as `IList<string>` which means the SDK library manages the instance of the list, but it does not manage the content, you can still change its content in multiple ways (for instance calling Add method, or instantiate an instance of the model using the `collection initializer` syntax)
For immutable lists, the type is generated as `IReadOnlyList<string>`.

If your case is that you found there is no way to populate items into the list, I believe this should answer your question, you just need to call `Add` on the property or use this syntax to instantiate the model:
```csharp
var model = new Model()
{
	CollectionProperty = {
		"item1", "item2"
	}
};
```
If you want to put an existing collection into the `CollectionProperty`, you might have to do it in a for loop or write an extension method such as
```csharp
public static void AddRange<T>(this IList<T> list, IEnumerable<T> items)
{
	foreach (var item in items)
	{
		list.Add(item);
	}
}
```

But if you insist to add setter on that property, you can change it by customization code, but I have to warn you ahead of time, it might be not so convenient to use outside our `azure-sdk-for-net` repo, because it now contains quite a few pit holes.
Essentially, you could add a partial class like this:
```csharp
namespace Microsoft.PowerBI.Api.Models
{
    public partial class EffectiveIdentity
	{
        /// <summary> An array of datasets for which this identity applies. </summary>
        public IList<string> Datasets { get; set; }
	}
```
Just duplicate the properties you desire to change in this new partial class (making sure the namespace is the same as the generated class). Initially you will see compilation errors of duplicated properties, please ignore it and regenerate your library.
If it is working fine, you will see the property `Datasets` disappears from the generated class, and now your property has a setter.

The customization functionality might not work well if some appearing-totally-irrelevant configurations are set properly. Please have a try and see what happens so that I could see what we have to do to make it work.
As a starter, please ensure the generator `Microsoft.Azure.AutoRest.CSharp` is listed as a private asset dependency of your generated library, also please ensure there is a `output-folder` configuration specified in your `readme.md` or `autorest.md` or your command line arguments, and its value is **an absolute path**. These are three things we have to have to make sure the customization code functionalities to work properly.

**Comment by KotanaSai21** [comment] 2024-04-08 09:53
@ArcturusZhang , Thanks for your response and it's never too late. We followed the first approach you suggested and were able to set the values now. 

However we're facing one last issue with our migration is that we're getting duplicate switch cases of same status code in generated files. Here is the GitHub Issue with more information https://github.com/Azure/autorest.csharp/issues/4550.

Could you please provide your inputs on this issue? Thanks a lot.

**Comment by ArcturusZhang** [comment] 2024-04-15 08:14
Since "no setters" for collection properties is by-design, and you are able to set values for those collections, I would close this issue.
Thank you

**Closed by ArcturusZhang** 2024-04-15 08:14 UTC
Labels: customer-reported, question

**Comment by PRK0001** [comment] 2024-04-24 12:42
@ArcturusZhang, 
I am facing similar issue with the setting the property. We have this autogenerated code from autorest.
```
public enum FruitsType
{ 
    Apple,
    Orange
 }

Public class Derived_Fruits {
 public FruitsType fruitstype { get; }
}
```
After creating an instance of Derived_Fruits in our code, we're unable to set the fruits property by using add method.  We want to set the fruit type in our code and we're getting this error `Property or indexer 'Derived_Fruits.FruitsType' cannot be assigned to -- it is read only`. Currently we're setting the property as below but getting error.
`Derived_FruitType = FruitsType.Orange;`

In the above if it's mutable list we can use add method to set the property. But here how can we set the property if the type is enum ? Could you please help us to resolve this issue?

**Comment by ArcturusZhang** [comment] 2024-04-26 02:37
> @ArcturusZhang, I am facing similar issue with the setting the property. We have this autogenerated code from autorest.
> 
> ```
> public enum FruitsType
> { 
>     Apple,
>     Orange
>  }
> 
> Public class Derived_Fruits {
>  public FruitsType fruitstype { get; }
> }
> ```
> 
> After creating an instance of Derived_Fruits in our code, we're unable to set the fruits property by using add method. We want to set the fruit type in our code and we're getting this error `Property or indexer 'Derived_Fruits.FruitsType' cannot be assigned to -- it is read only`. Currently we're setting the property as below but getting error. `Derived_FruitType = FruitsType.Orange;`
> 
> In the above if it's mutable list we can use add method to set the property. But here how can we set the property if the type is enum ? Could you please help us to resolve this issue?

I do not know details on your models, could you share more details on that?
There are quite a few cases that our generator will not generate the setters, one of the cases I have discussed in this issue when the property is a collection, other cases are mainly about "the generator thinks given the context of how the model is used in your operations, the setter is not needed".
For example, your `Derived_Fruits` may **only** be used as `output` by your operations, it is never directly or indirectly used as an input, the generator will not generate the setter for all the properties on the model.

I also do not know the purpose you want to set it. If you are calling an operation and this model is used in the request, this could be a bug, please attach more details on this (maybe in a new issue and link this one) so that we could take a look.
If your purpose it unit test, and asserting the response to have certain things, it is by design that you cannot just new the instance and assign values to its properties. Instead, you could use the model factory. There is a static `XXXModelFactory` class generated, and those models with "non-settable" properties should have a static method in this model factory, which is allowing you to set anything on the model.
The last is a workaround, you could always use this way to "force set" a property using the `ModelReaderWriter` like this:
```csharp
var data = BinaryData.FromObjectAsJson(new {
	fruitstype = "Orange",
	// other properties if any
}); // please note here we are using an anonymous object to create a json, therefore here the property name should be the json property name!
var instance = ModelReaderWriter.Read<Derived_Fruits>(data);
```
and in the `instance`, the `fruitstype` property should be properly set.

An additional information is that, specs, are not object oriented, you cannot imagine if an operation taking a `Base`, and we could pass a `Derived` json to the operation. This is not true unless the `Base` has a discriminator.
Therefore if your case is you have an operation taking a `Base` (without discriminator), and the `Base` has a `Derived`, and the generator (by design) will consider the type `Derived` not used in any input, because of the reason I said above. In this case, you should fix your spec to include a discriminator so that your `Base` model is polymorphic.
