### ISSUE TITLE
Add protocol send method to Client class

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4562] opened 2024-04-09 22:08 UTC
This includes calling RestClient CreateRequest method as well as handling the response to send back to the caller.

Migrate this writer helper: https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/ResponseWriterHelpers.cs

**Comment by m-nash** [comment] 2024-06-04 20:44
duplicate of https://github.com/microsoft/typespec/issues/3213

**Closed by m-nash** 2024-06-04 20:44 UTC
Labels: MGC
